-- 1
INSERT INTO CATEGORY (ID_CATEGORY, NAME_CATEGORY, DATE_CREATION)
VALUES (1,'FOOD','2026-08-24')
INSERT INTO CATEGORY (ID_CATEGORY, NAME_CATEGORY, DATE_CREATION)
VALUES (2,'ELETRONICS','2026-08-24')
SELECT * FROM CATEGORY

-- 2
INSERT INTO SUPPLIER (ID_SUPPLIER, DOCUMENT, LEGAL_NAME)
VALUES (1,'12345678912345','JACK')
INSERT INTO SUPPLIER (ID_SUPPLIER, DOCUMENT, LEGAL_NAME)
VALUES (2,'12345678912346','EDWARD')

-- 3
INSERT INTO PRODUCT (ID_PRODUCT, DESCRIPTION, ID_CATEGORY, ID_SUPPLIER)
VALUES (1, 'MOUSE', 2, 1)
INSERT INTO PRODUCT (ID_PRODUCT, DESCRIPTION, ID_CATEGORY, ID_SUPPLIER)
VALUES (2, 'SNIKERS', 1, 2)
INSERT INTO PRODUCT (ID_PRODUCT, DESCRIPTION, ID_CATEGORY, ID_SUPPLIER)
VALUES (3, 'TV', 2, 1)

-- 4
INSERT INTO CLIENT (ID_CLIENT, NAME_CLIENT)
VALUES (1, 'JHON')
INSERT INTO EMPLOYEE (ID_EMPLOYEE, NAME_FULL, WAGE, DATE_HIRE)
VALUES (1, 'CRASH', 1000, '2026-08-23')
INSERT INTO SALES (ID_SALE, DATE_SALE, TOTAL, ID_EMPLOYEE, ID_CLIENT)
VALUES (1, '2026-08-24', 35.25, 1, 1)

-- 5
INSERT INTO SALES_ITEMS (ID_SALE, ID_PRODUCT, QUANTITY, UNIT_PRICE)
VALUES (1,1,2,2.5)
INSERT INTO SALES_ITEMS (ID_SALE, ID_PRODUCT, QUANTITY, UNIT_PRICE)
VALUES (1,2,2,5)
SELECT * FROM SALES_ITEMS